version: "3.9"

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: chaves
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d chaves"]
      interval: 5s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./app/sql:/docker-entrypoint-initdb.d

  web:
    build: ./app
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_NAME: chaves
      DB_USER: admin
      DB_PASS: admin
      PYTHONPATH: /app/src
    ports:
      - "5000:5000"

volumes:
  pgdata:
